version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_simulation
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "8081:80"
